[package]
name = "rusic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
iced = { version = "0.12.1", features = ["image", "svg"] }
rodio = "0.19.0"
lofty = "0.20.1"
anyhow = "1.0.86"
serde_json = "1.0.120"
rfd = "0.14.1"
